swipe:
  3:
    left:
      command: "xdotool key alt+super+Left" # Move window one monitor to the left
    right:
      command: "xdotool key alt+super+Right" # Move window one monitor to the right
    up:
      command: "xdotool key ctrl+super+Up" # Move to workspace above
    down:
      command: "xdotool key ctrl+super+Down" # Move to workspace below
  4:
    left:
      command: "xdotool key super " # activity
    right:
      command: "xdotool key super" # activity
    up:
      command: "xdotool key alt+super+Up" # Move window one workspace up
    down:
      command: "xdotool key alt+super+Down" # Move window one workspace down
pinch:
  2:
    in:
      command: "xdotool key ctrl+plus" # Zoom in
      threshold: 0.1
    out:
      command: "xdotool key ctrl+minus" # Zoom out
      threshold: 0.1

threshold:
  swipe: 1
  pinch: 1

interval:
  swipe: 1
  pinch: 1   

